steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ih-aas', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ih-aas']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'ih-aas', 
         '--image', 'gcr.io/$PROJECT_ID/ih-aas', 
         '--platform', 'managed', 
         '--region', 'us-central1']
images:
- gcr.io/$PROJECT_ID/ih-aas
